### ISSUE TITLE
The proxy router isn't handling streaming responses from the server correctly

### ISSUE THREAD

**Issue by mrakgr** [Lumerin-protocol/Morpheus-Lumerin-Node#289]
![image](https://github.com/user-attachments/assets/7f5a6e26-7018-47e9-9302-8216c21a2aff)

I recently created the `cognitivecomputations/dolphin-2.9.2-qwen2-72b` model on your testnet chain and when I try using it as a consumer using the desktop UI on my windows PC, I get the above errors on the provider side in the Mor proxy. I think it's trying to convert the response into JSON instead of streaming them back to the consumer. I've already verified that the LiteLLM proxy and the vLLM model servers are streaming the responses correctly, meaning this is an error in the Morpheus proxy router.

**Comment by mrakgr** [comment]
It's saying right there that it's trying to decode the response, which it shouldn't be doing.

**Comment by mrakgr** [comment]
The commit I am on [is](https://github.com/Lumerin-protocol/Morpheus-Lumerin-Node/commit/43214ac082afa468a8364f52b6bcca0ae87a6fd7). I built it using `./build.sh` and am running the proxy router using `make run`.

**Comment by mrakgr** [comment]
What I expected is the request would work. What I got is the JSON decoding error in the screenshot.

**Comment by mrakgr** [comment]
Here is how the responses look like. I copy pasted this from the middle of the stream. They always start with `data` which isn't valid JSON.

```
data: {"id":"chatcmpl-cdde9de7-7070-4b63-af49-f11554c2a165","object":"text_completion","created":1732201518,"model":"meta-llama/Llama-3.2-3B","choices":[{"index":0,"text":"im"}],"usage":{"completion_tokens":0,"prompt_tokens":0,"total_tokens":0}}
data: {"id":"chatcmpl-cdde9de7-7070-4b63-af49-f11554c2a165","object":"text_completion","created":1732201518,"model":"meta-llama/Llama-3.2-3B","choices":[{"index":0,"text":"_start"}],"usage":{"completion_tokens":0,"prompt_tokens":0,"total_tokens":0}}
data: {"id":"chatcmpl-cdde9de7-7070-4b63-af49-f11554c2a165","object":"text_completion","created":1732201518,"model":"meta-llama/Llama-3.2-3B","choices":[{"index":0,"text":"|"}],"usage":{"completion_tokens":0,"prompt_tokens":0,"total_tokens":0}}
data: {"id":"chatcmpl-cdde9de7-7070-4b63-af49-f11554c2a165","object":"text_completion","created":1732201518,"model":"meta-llama/Llama-3.2-3B","choices":[{"index":0,"text":">"}],"usage":{"completion_tokens":0,"prompt_tokens":0,"total_tokens":0}}
data: {"id":"chatcmpl-cdde9de7-7070-4b63-af49-f11554c2a165","object":"text_completion","created":1732201518,"model":"meta-llama/Llama-3.2-3B","choices":[{"index":0,"text":"user"}],"usage":{"completion_tokens":0,"prompt_tokens":0,"total_tokens":0}}
data: {"id":"chatcmpl-cdde9de7-7070-4b63-af49-f11554c2a165","object":"text_completion","created":1732201518,"model":"meta-llama/Llama-3.2-3B","choices":[{"index":0,"text":"\n"}],"usage":{"completion_tokens":0,"prompt_tokens":0,"total_tokens":0}}
data: {"id":"chatcmpl-cdde9de7-7070-4b63-af49-f11554c2a165","object":"text_completion","created":1732201518,"model":"meta-llama/Llama-3.2-3B","choices":[{"index":0,"text":"Do"}],"usage":{"completion_tokens":0,"prompt_tokens":0,"total_tokens":0}}
data: {"id":"chatcmpl-cdde9de7-7070-4b63-af49-f11554c2a165","object":"text_completion","created":1732201518,"model":"meta-llama/Llama-3.2-3B","choices":[{"index":0,"text":" you"}],"usage":{"completion_tokens":0,"prompt_tokens":0,"total_tokens":0}}
data: {"id":"chatcmpl-cdde9de7-7070-4b63-af49-f11554c2a165","object":"text_completion","created":1732201518,"model":"meta-llama/Llama-3.2-3B","choices":[{"index":0,"text":" want"}],"usage":{"completion_tokens":0,"prompt_tokens":0,"total_tokens":0}}
data: {"id":"chatcmpl-cdde9de7-7070-4b63-af49-f11554c2a165","object":"text_completion","created":1732201518,"model":"meta-llama/Llama-3.2-3B","choices":[{"index":0,"text":" to"}],"usage":{"completion_tokens":0,"prompt_tokens":0,"total_tokens":0}}
data: {"id":"chatcmpl-cdde9de7-7070-4b63-af49-f11554c2a165","object":"text_completion","created":1732201518,"model":"meta-llama/Llama-3.2-3B","choices":[{"index":0,"text":" leave"}],"usage":{"completion_tokens":0,"prompt_tokens":0,"total_tokens":0}}
```

**Comment by abs2023** [comment]
@mrakgr what llm server are you using (Llama.cpp or something else?) 
in your models-config.json what is the url (you can obfuscate the dns or ip address)...but the url should have /v1 as a suffix if it's an openai compatible engine.

**Comment by mrakgr** [comment]
```json
{
  "0x5c6a8dd17e4b0d705a8f8b66a2a301db6f1486a0a4034271ff17f856fe7ec508": {
      "modelName": "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF",
      "apiType": "openai",
      "apiKey": "...",
      "apiUrl": "http://localhost:23330"
  },
  "0x00e503aba8d1faa67c5f232a6ad76626f7d5dd6af61ae36a95dc1ef11e8612a0": {
      "modelName": "meta-llama/Llama-3.2-3B",
      "apiType": "openai",
      "apiKey": "...",
      "apiUrl": "http://localhost:23330"
  },
  "0xfe4cc20404f223f336f241fa16748b91e8ff1d54141203b0882b637ead9fef79": {
      "modelName": "NousResearch/Hermes-2-Theta-Llama-3-8B",
      "apiType": "openai",
      "apiKey": "...",
      "apiUrl": "http://localhost:23330"
  },
  "0x27cf27d8d653d548c41619c56b1af3d5c8579d8c5049af18f67e03bb59366837": {
      "modelName": "cognitivecomputations/dolphin-2.9.2-qwen2-72b",
      "apiType": "openai",
      "apiKey": "...",
      "apiUrl": "http://localhost:23330"
  }
}
```

**Comment by mrakgr** [comment]
> what llm server are you using (Llama.cpp or something else?)

The Morpheus proxy server -> LiteLLM proxy server -> vLLM model server.

**Comment by mrakgr** [comment]
The LiteLLM proxy server is running on the same node as the Mor proxy router which is why the URL is pointing to localhost.

**Comment by abs2023** [comment]
you need to add /v1 to end end of your apiURLs ... you're not querying the same interface that you would if you connected directly.  Please see https://github.com/Lumerin-protocol/Morpheus-Lumerin-Node/blob/dev/docs/models-config.json.md for reference. 
`"apiUrl": "http://localhost:23330"` should be `"apiUrl": "http://localhost:23330/v1"

that's at least a first place to start ... as for daisy chaining to LiteLLM proxy and then vLLM model, that is not a design pattern we have looked at.  We are expecting  proxy-router --> llm server

**Comment by mrakgr** [comment]
> `"apiUrl": "http://localhost:23330"` should be `"apiUrl": `[http://localhost:23330/v1`](http://localhost:23330/v1%60)

I am going to try doing what you suggest, but I am not expecting much from it. I already ran into this same issue with LiteLLM. It would convert the `/v1` endpoints to regular ones and I'd get 404 errors. I fixed that by adding `/v1` into the `config.yaml` that LiteLLM uses. It looks like this right now, and this does work properly.

```yaml
model_list:
- litellm_params:
    api_base: "http://192.168.69.83:23331/v1"
    api_key: "..."
    model: "openai/nvidia/Llama-3.1-Nemotron-70B-Instruct-HF"
  model_info:
    author: "TODO"
    description: "TODO"
  model_name: "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF"
- litellm_params:
    api_base: "http://192.168.69.74:23331/v1"
    api_key: "..."
    model: "openai/cognitivecomputations/dolphin-2.9.2-qwen2-72b"
  model_info:
    author: "TODO"
    description: "TODO"
  model_name: "cognitivecomputations/dolphin-2.9.2-qwen2-72b"
- litellm_params:
    api_base: "http://192.168.69.76:23331/v1"
    api_key: "..."
    model: "openai/meta-llama/Llama-3.2-3B"
  model_info:
    author: "TODO"
    description: "TODO"
  model_name: "meta-llama/Llama-3.2-3B"
- litellm_params:
    api_base: "http://192.168.69.78:23331/v1"
    api_key: "..."
    model: "openai/NousResearch/Hermes-2-Theta-Llama-3-8B"
  model_info:
    author: "TODO"
    description: "TODO"
  model_name: "NousResearch/Hermes-2-Theta-Llama-3-8B"
```
